=== khthana/CE_Project2/Project46/Internet Learning System 2/Execute/Tomcat/jchatbox/applet/skin_comics/jcbskin.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- jChatBox client Applet Skin -->
<!ELEMENT JCBSKIN (LOGINPANEL, CHATPANEL)>
<!ATTLIST JCBSKIN
    NAME CDATA #REQUIRED
>
<!ELEMENT LOGINPANEL (LABEL+, BUTTON, TEXTFIELD+, CHOICE)>
<!ATTLIST LOGINPANEL
    FONTNAME CDATA #IMPLIED
    FONTSIZE CDATA #IMPLIED
    FONTSTYLE CDATA #IMPLIED
    BGCOLOR CDATA #IMPLIED
    BGIMAGE CDATA #IMPLIED
>
<!ELEMENT CHATPANEL (LABEL+, BUTTON+, TEXTFIELD, TEXTAREA, LIST)>
<!ATTLIST CHATPANEL
    FONTNAME CDATA #IMPLIED
    FONTSIZE CDATA #IMPLIED
    FONTSTYLE CDATA #IMPLIED
    BGCOLOR CDATA #IMPLIED
    BGIMAGE CDATA #IMPLIED
>
<!ELEMENT LABEL (#PCDATA)>
<!ATTLIST LABEL
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
>
<!ELEMENT BUTTON (#PCDATA)>
<!ATTLIST BUTTON
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
    BGCOLOR CDATA #REQUIRED
>
<!ELEMENT TEXTFIELD EMPTY>
<!ATTLIST TEXTFIELD
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
    BGCOLOR CDATA #REQUIRED
>
<!ELEMENT CHOICE EMPTY>
<!ATTLIST CHOICE
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
    BGCOLOR CDATA #REQUIRED
    FIRSTITEM CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    SEPARATOR CDATA #IMPLIED
>
<!ELEMENT TEXTAREA EMPTY>
<!ATTLIST TEXTAREA
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
    BGCOLOR CDATA #REQUIRED
    JOINMSG CDATA #IMPLIED
    QUITMSG CDATA #IMPLIED
    PRIVATEMSG CDATA #IMPLIED
    ALLMSG CDATA #IMPLIED
>
<!ELEMENT LIST EMPTY>
<!ATTLIST LIST
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
    BGCOLOR CDATA #REQUIRED
    TITLE CDATA #REQUIRED
    SEPARATOR CDATA #REQUIRED
>

=== khthana/CE_Project2/Project46/Internet Learning System 2/Execute/Tomcat/jchatbox/applet/skin_multilanguage/jcbskin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- jChatBox client Applet Skin -->
<!DOCTYPE JCBSKIN SYSTEM "jcbskin.dtd">
<JCBSKIN NAME="MultiLanguages">
    <LOGINPANEL FONTNAME="Helvetica" FONTSIZE="12" FONTSTYLE="bold" BGCOLOR="3366AA">
        <LABEL ID="USERNAME" X="7" Y="14" WIDTH="85" HEIGHT="23" COLOR="FFFFFF">multilanguage</LABEL>
        <LABEL ID="CHATROOMS" X="5" Y="86" WIDTH="117" HEIGHT="22" COLOR="FFFFFF">multilanguage</LABEL>
        <LABEL ID="NAME" X="292" Y="12" WIDTH="190" HEIGHT="22" COLOR="FFFFCC">multilanguage</LABEL>
        <LABEL ID="DATE" X="292" Y="34" WIDTH="206" HEIGHT="22" COLOR="FFFFCC">multilanguage</LABEL>
        <LABEL ID="SUBJECT" X="292" Y="55" WIDTH="190" HEIGHT="22" COLOR="FFFFCC">multilanguage</LABEL>
        <LABEL ID="ERROR" X="5" Y="42" WIDTH="267" HEIGHT="22" COLOR="FF0000"/>
        <LABEL ID="WELCOME" X="344" Y="290" WIDTH="228" HEIGHT="51" COLOR="000022">http://www.javazoom.net</LABEL>
        <BUTTON ID="LOGIN" X="218" Y="16" WIDTH="68" HEIGHT="21" COLOR="000022" BGCOLOR="CCCCFF">multilanguage</BUTTON>
        <TEXTFIELD ID="USERNAME" X="94" Y="16" WIDTH="117" HEIGHT="20" COLOR="000055" BGCOLOR="9999FF"/>
        <CHOICE ID="ROOMS" X="130" Y="87" WIDTH="160" HEIGHT="20" COLOR="000055" BGCOLOR="99AAFF" FIRSTITEM="multilanguage"/>
    </LOGINPANEL>
    <CHATPANEL FONTNAME="Helvetica" FONTSIZE="12" FONTSTYLE="bold" BGCOLOR="3366AA">
        <LABEL ID="MESSAGE" X="4" Y="268" WIDTH="63" HEIGHT="22" COLOR="FFFFFF">multilanguage</LABEL>
        <LABEL ID="NAME" X="4" Y="295" WIDTH="190" HEIGHT="22" COLOR="CCCCFF">multilanguage</LABEL>
        <BUTTON ID="SEND" X="324" Y="270" WIDTH="68" HEIGHT="21" COLOR="000022" BGCOLOR="CCCCFF">multilanguage</BUTTON>
        <BUTTON ID="REFRESH" X="396" Y="270" WIDTH="82" HEIGHT="21" COLOR="222222" BGCOLOR="CCCCDD">multilanguage</BUTTON>
        <BUTTON ID="LOGOUT" X="396" Y="294" WIDTH="70" HEIGHT="21" COLOR="660000" BGCOLOR="CCCCDD">multilanguage</BUTTON>
        <TEXTFIELD ID="MESSAGE" X="65" Y="270" WIDTH="250" HEIGHT="21" COLOR="000055" BGCOLOR="9999FF"/>
        <TEXTAREA ID="MESSAGES" X="10" Y="13" WIDTH="368" HEIGHT="246" COLOR="000033" BGCOLOR="DDDDFF" JOINMSG="multilanguage" QUITMSG="multilanguage" PRIVATEMSG="multilanguage" ALLMSG="multilanguage"/>
        <LIST ID="USERS" X="390" Y="13" WIDTH="100" HEIGHT="245" COLOR="000066" BGCOLOR="CCCCFF" TITLE="multilanguage" SEPARATOR="==========="/>
    </CHATPANEL>
</JCBSKIN>
